sudo: required
language: python
python:
  - "3.6"
services:
- docker
branches:
  except:
  - master
cache:
- pip
- npm
addons:
  apt:
    update: true
    packages:
    - nodejs
    - npm
install:
- npm install
- pip install hooks4git
before_script:
- hooks4git -t pre-commit
script:
- ./build.sh --quiet
- ./cpp/build.sh --quiet
- ./python/build.sh --quiet
- ./nodejs/build.sh --quiet
- ./java/build.sh --quiet
- ./android/build.sh --quiet
- ./android/ndk/build.sh --quiet
after_script:
- set -e && ./test-all.sh
- docker images
notifications:
  email: true