sudo: required
language: generic
services:
- docker
branches:
  except:
  - master
before_install:
- sudo apt-get update -qq
install:
- npm install -g npm
- npm install -g dockerfile_lint
- npm install -g markdownlint-cli
- npm install -g travis-lint
before_script:
- travis-lint .travis.yml
- dockerfile_lint Dockerfile
- markdownlint README.md
script:
- ./build.sh --quiet
- ./cpp/build.sh --quiet
- ./python/build.sh --quiet
- ./nodejs/build.sh --quiet
- ./java/build.sh --quiet
- ./android/build.sh --quiet
- ./android/ndk/build.sh --quiet
after_script:
- set -e && ./test-all.sh
- docker images
notifications:
  email: true