sudo: required
language: generic
services:
- docker
branches:
  except:
  - master
before_install:
- sudo apt-get update -qq
install:
- npm install -g npm
- npm install
before_script:
- pip install hooks4git
- hooks4git -t pre-commit
script:
- ./build.sh --quiet
- ./cpp/build.sh --quiet
- ./python/build.sh --quiet
- ./nodejs/build.sh --quiet
- ./java/build.sh --quiet
- ./android/build.sh --quiet
- ./android/ndk/build.sh --quiet
after_script:
- set -e && ./test-all.sh
- docker images
notifications:
  email: true