sudo: required
language: generic
services:
- docker
branches:
  except:
  - master
before_install:
- sudo apt-get update -qq
install:
- npm install -g npm
- npm install -g dockerfile_lint
- npm install -g markdownlint-cli
- npm install -g travis-lint
before_script:
- travis-lint .travis.yml
- dockerfile_lint Dockerfile
- markdownlint README.md
script:
- ./build.sh
- ./cpp/build.sh
- ./python/build.sh
- ./nodejs/build.sh
- ./java/build.sh
- ./android/build.sh
- ./android/ndk/build.sh
after_script:
- ./test.sh
- cd cpp && ./test.sh && cd ..
- cd python && ./test.sh && cd ..
- cd nodejs && ./test.sh && cd ..
- cd java && ./test.sh && cd ..
- cd android && ./test.sh && cd ..
- cd android/ndk && ./test.sh && cd ../..
notifications:
  email: true